### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by F3F5** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#33]
```[06:18:51 ERROR]: Could not load 'plugins/AntiRedstoneClock-Remastered-1.0.0-SNAPSHOT+6f51ea8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/onelitefeather/antiredstoneclockremastered/api/WorldGuardSupport
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:250) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:638) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/onelitefeather/antiredstoneclockremastered/api/WorldGuardSupport
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.init(PluginClassLoader.java:78) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
... 6 more
Caused by: java.lang.ClassNotFoundException: net.onelitefeather.antiredstoneclockremastered.api.WorldGuardSupport
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]```

**Comment by F3F5** [comment]
```[06:43:30 ERROR]: Error occurred while enabling AntiRedstoneClock-Remastered v1.0.0-SNAPSHOT+6f51ea8 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/ComponentLike
        at net.onelitefeather.antiredstoneclockremastered.AntiRedstoneClockRemastered.enableRedstoneClockService(AntiRedstoneClockRemastered.java:133) ~[?:?]
        at net.onelitefeather.antiredstoneclockremastered.AntiRedstoneClockRemastered.onEnable(AntiRedstoneClockRemastered.java:48) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:311) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:450) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:411) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:349) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:638) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.ComponentLike
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more```

**Comment by TheMeinerLP** [comment]
Have you build by your self ? 
Also which version ?

**Comment by TheMeinerLP** [comment]
Also we don't support below 1.17.1

**Comment by F3F5** [comment]
> Have you build by your self ? Also which version ?

latest and yourself (tested all 2 jars)

**Comment by TheMeinerLP** [comment]
More specific please

**Comment by F3F5** [comment]
build yourself and tested 2 jars after build

**Comment by TheMeinerLP** [comment]
Please give a specific version of the plugin and server.

**Comment by F3F5** [comment]
plugin version 6f51ea86b96da1f1fb51b10cf38aa539841dee67 
server Reaper 1.12.2 without plugins (only your)

**Comment by TheMeinerLP** [comment]
Such versions and fork a not supported!

**Comment by F3F5** [comment]
fork but with bugs 
i'll continue to use original
