### ISSUE TITLE
Error using command /arcm display

### ISSUE THREAD

**Issue by moonies44** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#55]
hello,

im on Paper git-paper-196 1.20.1 R0.1-SNAPSHOT.

when using the command /arcm display a read error displays in chat and console reports error

````[21:08:26] [Server thread/INFO]: Moonstah issued server command: /arcm display
[21:08:26] [ForkJoinPool.commonPool-worker-2/ERROR]: [AntiRedstoneClock-Remastered] An unhandled exception was thrown during command execution
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.TranslatableComponent net.kyori.adventure.text.TranslatableComponent.arguments(net.kyori.adventure.text.ComponentLike[])'
    at net.onelitefeather.antiredstoneclockremastered.commands.DisplayActiveClocksCommand.displayClocks(DisplayActiveClocksCommand.java:26) ~[AntiRedstoneClock-Remastered-1.0.1-all.jar:?]
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757) ~[?:?]
    at org.incendo.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[AntiRedstoneClock-Remastered-1.0.1-all.jar:?]
    at org.incendo.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:120) ~[AntiRedstoneClock-Remastered-1.0.1-all.jar:?]
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]````

**Comment by TheMeinerLP** [comment]
@moonies44 Update to latest version. I tested it at plain paper with 1.20 and 1.20.1
